### ISSUE TITLE
Missing HTML entity escaping

### ISSUE THREAD

**Issue by vlakoff** [FlominatorTM/wikiblame#13]
Search for "&lt;u&gt;", in a page *that does contain this string*.

Example:

Field | Value
----- | -----
Language | fr
Project | wikipedia
Page | Modèle:Méta bandeau d'événement récent
Search for | &lt;u&gt;

You will notice the results are erroneously underlined.

Looks like it also makes the search somehow infinite… ?! :trollface:

**Comment by FlominatorTM** [comment]
Congratulations. You found three bugs out of which one was in for years.
