### ISSUE TITLE
Endless cycle

### ISSUE THREAD

**Issue by jwbth** [FlominatorTM/wikiblame#20]
http://wikipedia.ramselehof.de/wikiblame.php?user_lang=en&lang=ru&project=wikipedia&article=Википедия%3AОформление+статей&needle=Обратите+внимание&skipversions=0&ignorefirst=0&limit=500&offtag=12&offmon=11&offjahr=2017&searchmethod=int&order=desc&binary_search_inverse=on&force_wikitags=on&user=
```
2 versions found
Comparing differences in 13:09, 20 October 2017 between 1 and 2 while coming from 2:OO 
Comparing differences in 14:54, 20 October 2017 between 0 and 1 while coming from 1:OO 
Deleting 1 earlier revisions, since removal must have been performed later
```
repeates indefinitely.

**Comment by vlakoff** [comment]
If it may help, I have just encountered an endless process too: http://wikipedia.ramselehof.de/wikiblame.php?user_lang=en&lang=fr&project=wikipedia&article=MediaWiki%3ACommon.js%2Fedit.js&needle=%2B+page_name+%2B&skipversions=0&ignorefirst=0&limit=5000&offmon=12&offtag=27&offjahr=2013&searchmethod=int&order=desc&binary_search_inverse=on&force_wikitags=on&user=

**Comment by ToBeFree** [comment]
http://wikipedia.ramselehof.de/wikiblame.php?project=wikipedia&article=Propriet%C3%A4r&needle=MP3&lang=de&limit=50000&offjahr=2013&offmon=07&offtag=19&offhour=14&offmin=19&searchmethod=int&order=desc&force_wikitags=off&user_lang=de&binary_search_inverse=on

**Comment by ToBeFree** [comment]
Die Versionsgeschichte des Artikels Proprietär wird nach MP3 als einfachem Text durchsucht
222 Versionen gefunden
Prüfe Änderung vom 20. Januar 2007, 15:54 Uhr zwischen 111 und 112 von 222 aus:OO
Lösche 109 frühere Versionen, da Löschung später vorgenommen worden sein muss

113 Versionen gefunden
Prüfe Änderung vom 01. Oktober 2008, 13:01 Uhr zwischen 56 und 57 von 113 aus:OO
Lösche 55 frühere Versionen, da Löschung später vorgenommen worden sein muss

58 Versionen gefunden
Prüfe Änderung vom 01. Oktober 2011, 19:48 Uhr zwischen 29 und 30 von 58 aus:OO
Lösche 27 frühere Versionen, da Löschung später vorgenommen worden sein muss

31 Versionen gefunden
Prüfe Änderung vom 02. Januar 2013, 18:28 Uhr zwischen 15 und 16 von 31 aus:OO
Lösche 14 frühere Versionen, da Löschung später vorgenommen worden sein muss

17 Versionen gefunden
Prüfe Änderung vom 03. April 2013, 05:23 Uhr zwischen 8 und 9 von 17 aus:OO
Lösche 7 frühere Versionen, da Löschung später vorgenommen worden sein muss

10 Versionen gefunden
Prüfe Änderung vom 28. Mai 2013, 07:24 Uhr zwischen 5 und 6 von 10 aus:OO
Lösche 3 frühere Versionen, da Löschung später vorgenommen worden sein muss

7 Versionen gefunden
Prüfe Änderung vom 03. Juni 2013, 06:39 Uhr zwischen 3 und 4 von 7 aus:OO
Lösche 2 frühere Versionen, da Löschung später vorgenommen worden sein muss

5 Versionen gefunden
Prüfe Änderung vom 09. Juni 2013, 09:37 Uhr zwischen 2 und 3 von 5 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

4 Versionen gefunden
Prüfe Änderung vom 09. Juni 2013, 09:37 Uhr zwischen 2 und 3 von 4 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

3 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 3 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

2 Versionen gefunden
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 1 und 2 von 2 aus:OO
Prüfe Änderung vom 19. Juli 2013, 12:19 Uhr zwischen 0 und 1 von 1 aus:OO
Lösche 1 frühere Versionen, da Löschung später vorgenommen worden sein muss

**Comment by FlominatorTM** [comment]
More cases from talk pages:
* http://wikipedia.ramselehof.de/wikiblame.php?user_lang=en&lang=en&project=wikipedia&article=Recurring+Saturday+Night+Live+characters+and+sketches+introduced+2011%E2%80%932012&needle=%27%27J-Pop&skipversions=0&ignorefirst=0&limit=500&offmon=3&offtag=8&offjahr=2019&searchmethod=int&order=desc&binary_search_inverse=on&force_wikitags=on&user=

* http:/wikipedia.ramselehof.de/wikiblame.php?user_lang=en&lang=en&project=wikipedia&article=Institute+of+Education+Sciences&needle=Clearinghouse&skipversions=0&ignorefirst=0&limit=500&offmon=6&offtag=20&offjahr=2018&searchmethod=int&order=desc&binary_search_inverse=on&user=

* http://wikipedia.ramselehof.de/wikiblame.php?user_lang=en&lang=en&project=wikipedia&article=Runge%E2%80%93Kutta+methods&needle=%7C%7C%7C&skipversions=0&ignorefirst=0&limit=500&offmon=11&offtag=15&offjahr=2018&searchmethod=int&order=desc&binary_search_inverse=on&force_wikitags=on&user=

* http://wikipedia.ramselehof.de/wikiblame.php?user_lang=en&lang=en&project=wikipedia&article=Media+in+Chicago&needle=WXAV&skipversions=0&ignorefirst=0&limit=500&offmon=2&offtag=12&offjahr=2019&searchmethod=int&order=desc&binary_search_inverse=on&user=
 
Problem is, that with the last queries the behavior sucks :(
