### ISSUE TITLE
Capitalized date separators

### ISSUE THREAD

**Issue by waldyrious** [FlominatorTM/wikiblame#24]
It looks like the date separators are getting capitalized. For example, in Portuguese the separator is `de` (as seen [here](https://github.com/FlominatorTM/wikiblame/blob/f15383ccdfbbf4f4b445979a56a2e7679dea3364/wikiblame_inc/pt.php#L51)), but in the interface they show up as `DE`:

<img width="444" alt="Screenshot 2019-07-03 at 15 11 59" src="https://user-images.githubusercontent.com/478237/60598649-f7da7f80-9da4-11e9-93ef-bf94f0af15cc.png">

**Comment by FlominatorTM** [comment]
This is a matter of translations, please correct them at https://translatewiki.net/wiki/Translating:WikiBlame

**Comment by tacsipacsi** [comment]
It’s capitalized in [wiki_functions.inc.php, line 167](https://github.com/FlominatorTM/wikiblame/blob/58fbe1c597c443a4ecfdf8de7c71be53d21fa4bb/shared_inc/wiki_functions.inc.php#L167) to make the YYYY, MM, DD placeholders case-insensitive. Maybe it should be changed to case-insensitive regex matches so that upper casing is not needed.

**Comment by FlominatorTM** [comment]
Thanks for reporting the problem and for finding the reason. I wasn't aware of this.
@tacsipacsi Would you might providing a merge request of your approach? My regexp capabilities are very limited ;)

As an alternative one could use [str_ireplace](https://www.php.net/manual/de/function.str-ireplace.php) at line 179, I think.

**Comment by waldyrious** [comment]
Wouldn't it suffice to simply remove `strtoupper`? That means the placeholders must be provided with the correct capitalization (e.g. "DD" instead of "dd"), but that's already the case in many date formatting syntaxes.

Besides, as far as I can tell, none of the current translations use those placeholders in lowercase anyway: 

```sh
❯ rg 'date_format.+dd' wikiblame_inc | wc -l
0

❯ rg 'date_format.+mm' wikiblame_inc | wc -l
0

❯ rg 'date_format.+yyyy' wikiblame_inc | wc -l
0

❯ rg 'date_format.+DD' wikiblame_inc | wc -l
112

❯ rg 'date_format.+MM' wikiblame_inc | wc -l
117

❯ rg 'date_format.+YYYY' wikiblame_inc | wc -l
106
```

**Comment by waldyrious** [comment]
The discrepancy in the counts above is due to translations which mistakenly localized the placeholders, btw:

- diq: ['RR MM, SSSS'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/diq.php#L45)
- es: ['MM DD, AAAA'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/es.php#L50)
- fr: ['JJ MM AAAA'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/fr.php#L50)
- fur: ['MM DD, AAAA'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/fur.php#L37)
- ie: ['MM DD, AAAA'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/ie.php#L37)
- ku-latn: ['RR.MM.SSSS'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/ku-latn.php#L39)
- lv: ['MM DD, GGGG'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/lv.php#L39)
- nah: ['MM II, XXXX'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/nah.php#L33)
- nb: ['MM DD, ÅÅÅÅ'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/nb.php#L43)
- scn: ['JJ MM AAAA'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/scn.php#L38)
- sk: ['DD MM RRRR'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/sk.php#L45)
- sv: ['MM DD, ÅÅÅÅ'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/sv.php#L47)
- tr: ['GG AA YYYY'](https://github.com/FlominatorTM/wikiblame/blob/f15383c/wikiblame_inc/tr.php#L50)

All of these should be fixed to use the literal tokens "DD", "MM" and "YYYY". But that's a different issue than this.

**Comment by FlominatorTM** [comment]
@siebrand : Can I simply delete the wrong translations in git or how do I get rid of them to have them retranslated?

**Comment by Nikerabbit** [comment]
I recommend to ping @translatewiki in the future to reach the whole team.

Deletion in the repo won't suffice. This would be a good case for a custom validator that prevents wrong translations. Then we can mark them as outdated or consider deleting, when we can be sure they won't be reintroduced.

**Comment by FlominatorTM** [comment]
Will try to remember and do that next time.

Where would such a custom validator be placed? How would it look like?

**Comment by Nikerabbit** [comment]
I'm am attempting to implement it. We have a new validator framework and this seems a good case for me to try it out myself.

**Comment by Nikerabbit** [comment]
https://gerrit.wikimedia.org/r/c/translatewiki/+/524669

**Comment by Abijeet** [comment]
Greetings,

I work with Niklas on the @translatewiki team. The patch mentioned by Niklas has been merged and deployed on Translatewiki.net.

Following validators / insertables have been added,

1. `MM DD, YYYY` - The exact strings - `YYYY`, `MM`, `DD` must be present in the translation.
2. Strings such as `__NEEDLE__` & `__REVISIONLINK__` must be present in the translation as is, without being translated.

If the user does not put any of these, they'll be receiving an error and cannot save their translation.

![image](https://user-images.githubusercontent.com/1685517/61857371-ac1d8080-aee1-11e9-8391-dd647046ff50.png)

**Comment by FlominatorTM** [comment]
Thanks. This looks pretty cool and intuitive. What do I need to do now to clean the translations mentioned at https://github.com/FlominatorTM/wikiblame/issues/24#issuecomment-513503896 ?

**Comment by Abijeet** [comment]
@FlominatorTM -  I'll get back to you on that. We've some limitation with this file format, I'll have to check a bit and see what will be the best approach.

**Comment by FlominatorTM** [comment]
@Abijeet Any news? If not, when may I ask again?

**Comment by Abijeet** [comment]
@FlominatorTM - Sorry about the delay. I'll try to get back to you by Wednesday this week.

**Comment by Abijeet** [comment]
@FlominatorTM  - You can go ahead and delete the translations that are not appropriate. Once done, please give me a link to the commit so I can do the same on Translatewiki.net. 

I assume that you have fallback to English configured in the source code if the translation does not exist?

**Comment by FlominatorTM** [comment]
Done that and yes, fallback in included.

**Comment by Abijeet** [comment]
I've removed the translations on Translatewiki.net. We ran an export today (45c74728dc9dbaeb0670c35c6a21a94fd597b082), and everything looks good

**Comment by Abijeet** [comment]
I've removed the translations on Translatewiki.net. We ran an export today (45c74728dc9dbaeb0670c35c6a21a94fd597b082), and everything looks good

**Comment by Abijeet** [comment]
I've removed the translations on Translatewiki.net. We ran an export today (45c74728dc9dbaeb0670c35c6a21a94fd597b082), and everything looks good

**Comment by FlominatorTM** [comment]
Seems to be fixed, right, @waldyrious ?

**Comment by waldyrious** [comment]
Yep, looks good now!

<img width="438" alt="Screenshot 2019-08-25 at 22 29 10" src="https://user-images.githubusercontent.com/478237/63656083-cddf8100-c787-11e9-8a97-fbb47de3f66e.png">
