### ISSUE TITLE
only found the first of two changes to article

### ISSUE THREAD

**Issue by skierpage** [FlominatorTM/wikiblame#38]
Thanks for this tool :heart:! I used it to find out who mistakenly added "Ringo" (Starr) to an article, and it does zero in on the [first edit that added him on 2007-10-04](https://en.wikipedia.org/w/index.php?title=I%27m_in_You&diff=prev&oldid=162318251). Unfortunately now that I've cleaned up the article, the search fails.

_But_, there was another, [later edit on 2008-05-30](https://en.wikipedia.org/w/index.php?title=I%27m_in_You&type=revision&diff=216483330&oldid=216007750) that also added "Ringo" to a different section. I couldn't figure out how to find that edit. I can't search linearly for it (the tool complains about too many revisions) and I can't add an ending date (or start date? it's very confusing) of the first edit to get the tool to search forward in time from that date. So I had to do my own binary search with View History's [Compare revisions] button.

Even if I set the start date to June 1 2008 and start oldest first, the tool doesn't find the addition, maybe because the first "Ringo" is always present. If the tool can only find an added string if it isn't already in the article, then something should mention that limitation. But shouldn't a linear search diff detect the second addition of the term? The diff should detect the new term. The more I fiddle with the settings, the less I understand the tool :wink:.

**Comment by tacsipacsi** [comment]
This tool checks versions, not diffs. In non-wikitext mode it couldn’t even reliably search diffs (Wikipedia itself has a visual diff mode lately, but it often omits changes). In wikitext mode, it’s theoretically possible, but operating on diffs would mean that simply moving a text within the article would be flagged as deletion and insertion, and also this big difference between wikitext and non-wikitext mode would be confusing. According to the [on-wiki documentation](https://en.wikipedia.org/wiki/User:Flominator/WikiBlame), the goal of this tool is to find passages, not single words, for which duplication is rarely a concern.

**Comment by FlominatorTM** [comment]
Hi, for me, the first search you mentioned, still works:
https://wikipedia.ramselehof.de/wikiblame.php?lang=en&project=wikipedia&tld=org&article=I%27m+in+You&needle=Ringo+Starr&skipversions=0&ignorefirst=0&limit=500&offtag=12&offmon=3&offjahr=2022&searchmethod=int&order=desc

For the second insertion you would have just needed a longer phrase, like this one:
https://wikipedia.ramselehof.de/wikiblame.php?lang=en&project=wikipedia&tld=org&article=I%27m+in+You&needle=%2C+%5B%5BRingo+Starr%5D%5D%2C&skipversions=0&ignorefirst=0&limit=500&offtag=12&offmon=3&offjahr=2022&searchmethod=int&order=desc

Kind regards
Flo
