### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by pols12** [FlominatorTM/wikiblame#42]
1. [Look for “nourrissons” in fr:Munster_(fromage)](http://wikipedia.ramselehof.de/wikiblame.php?user_lang=fr&lang=fr&project=wikipedia&tld=org&article=Munster+%28fromage%29&needle=nourrissons&skipversions=0&ignorefirst=0&limit=500&offtag=28&offmon=9&offjahr=2022&searchmethod=int&order=desc&user=)
2. Note WikiBlame considers that [21:12, 16 July 2022 revision](https://fr.wikipedia.org/w/index.php?title=Munster_%28fromage%29&oldid=195370256) has not the searched string, whereas it is the version which adds it.
3. The resulting diff is not the one which adds the searched string.

**Comment by FlominatorTM** [comment]
Interesting. It works when [querying for wikitext](http://wikipedia.ramselehof.de/wikiblame.php?user_lang=en&lang=fr&project=wikipedia&tld=org&article=Munster+%28fromage%29&needle=nourrissons&skipversions=0&ignorefirst=0&limit=500&offtag=28&offmon=9&offjahr=2022&searchmethod=int&order=desc&force_wikitags=on&user=) but not [with html](http://wikipedia.ramselehof.de/wikiblame.php?user_lang=de&lang=fr&project=wikipedia&tld=org&article=Munster+%28fromage%29&needle=nourrissons&skipversions=0&ignorefirst=0&limit=500&offtag=28&offmon=9&offjahr=2022&searchmethod=int&order=desc&user=)

**Comment by FlominatorTM** [comment]
Fixed with 43b9af27e4ca4619e3c181208c4d9d25a80eaa3c and patch provided by Wotheina
