### ISSUE TITLE
Link to this github repo

### ISSUE THREAD

**Issue by waldyrious** [FlominatorTM/wikiblame#43]
Possibly replacing the current [Contact](https://de.wikipedia.org/wiki/Benutzer%20Diskussion:Flominator/WikiBlame) link in the footer.

**Comment by FlominatorTM** [comment]
not sure, if non-developers would not be overwhelmed ...

**Comment by waldyrious** [comment]
If the link has a clear label (e.g. "source code") I think only the relevant audience would be interested in following it.

**Comment by FlominatorTM** [comment]
But the contact link implicitly already links to GitHub, giving the non-devs the chance to stay on their turf using the talk page

**Comment by waldyrious** [comment]
Alright, then how about having both a "Source code" and a "Feedback" in the footer?

Also, are you planning to keep maintaining that page for feedback? I thought you wanted to step away from the project, considering the "get rid of it" part of [this comment](https://github.com/FlominatorTM/wikiblame/pull/41#issuecomment-1323086338). Of course we could still have a wikipage somewhere, e.g. on meta, to avoid overwhelming non-developers, but then the question remains of who would keep tabs on that page...

**Comment by FlominatorTM** [comment]
Two links in the footer sound good to me.

For the moment, I would keep the feedback page, since I didn't really find any way to properly hand over the project to somebody. Also I'm checking it at least once per month, in case something goes down the drain.
