### ISSUE TITLE
Wikiblame tool is down

### ISSUE THREAD

**Issue by Manu1400** [FlominatorTM/wikiblame#48]
tested with Google Chrome, this day, from France: KO

# additional
https://www.ramselehof.de/ (personal website): OK

**Comment by FlominatorTM** [comment]
Somehow my hoster changed something that broke the subdomain. It's fixed now, but it will show an SSL error message for the moment, since the certificate doesn't really fit.

You can use https://www.ramselehof.de/wikipedia/wikiblame.php instead for the moment.

**Comment by FlominatorTM** [comment]
Was fixed a few days later, but I forgot to close this. Now we also have https support!
