### ISSUE TITLE
Wikiblame returns 403 "Forbidden" error

### ISSUE THREAD

**Issue by jdcrutch** [FlominatorTM/wikiblame#5]
Hello.  When I try to use Wikiblame, I get a 403 "Forbidden" error.  This happens with different browsers and different devices.  Hope you can fix it soon.

**Comment by FlominatorTM** [comment]
Am aware of the problem and waiting for my webspace provider to react. Thanks for the report

**Comment by FlominatorTM** [comment]
Fixed.

**Comment by jdcrutch** [comment]
Thanks!
