### ISSUE TITLE
Add the link to the diff again in the end in bigger and bold characters

### ISSUE THREAD

**Issue by tbertels** [FlominatorTM/wikiblame#6]
The use of WikiBlame is to find the diff showing where the searched changes happened.
However, currently that diff link isn't any more highlighted than the other links and is difficult to locate in day to day use. New users even don't find that link sometimes or it may take them some time (see [here](https://de.wikipedia.org/wiki/Benutzer_Diskussion:Flominator/WikiBlame#Suggestion)).

So it would very useful to add again that link after the end of the search with something like **Link to diff** (in bigger font).

**Comment by FlominatorTM** [comment]
Congratulations for writing the description the way you did and not the others. That made pop up the solution I just implemented. Please tell me if is ok like this and re-open this issue if not.

**Comment by FlominatorTM** [comment]
Might be interesting for @he7d3r as well

**Comment by tbertels** [comment]
Thank you for the fix!
It looks great, however I really think you should make the text in bold, I actually didn't notice it at first.
In case you prefer not to do so, can we do it in the translations, and is it with <b></b>?

**Comment by tbertels** [comment]
It works fine with `<b></b>` by the way, see the [French translation](https://translatewiki.net/wiki/Wikimedia:Messages%5Cx5b%27here%27%5Cx5d/fr).
A longer text than "here" like that one makes it also easier to click on the link, and it's better in general to give links a name with the meaning of what they do, like in the wiki.

**Comment by FlominatorTM** [comment]
The idea of having "uncontrolled html tags" in the translation worries me a little. Maybe I should make the link bold myself and label it "see change found" or something?

**Comment by tbertels** [comment]
Yes, it would be a great idea, as a longer bold text is easier to see and click.

**Comment by FlominatorTM** [comment]
@waldyrious fixed it with https://github.com/FlominatorTM/wikiblame/pull/10

I assume, it's no ok lik this?
