### ISSUE TITLE
Update pt translation

### ISSUE THREAD

**Issue by he7d3r** [FlominatorTM/wikiblame#7]
Hi!
Could you update the tool so that the following translation is fixed?
https://translatewiki.net/w/i.php?title=Wikimedia%3AMessages%5Cx5b%27first_version_present%27%5Cx5d%2Fpt&type=revision&diff=6821236&oldid=6789559

**Comment by FlominatorTM** [comment]
Must have slipped. I just re-uploaded the language files.

**Comment by he7d3r** [comment]
Thanks!
