### ISSUE TITLE
default language

### ISSUE THREAD

**Issue by zemiak1** [FlominatorTM/wikiblame#9]
I edit wiki in three language (sk,cs,en). 
If I run WikiBlame from **cs** history page, it set default language to **sk** (may be for I have sk enviroment default set), 
but this is not correct intuitive behavior because when I press search, I think so in that time I search cz page from I started run wikiblame, but it search in sk page with same name

**Comment by FlominatorTM** [comment]
How exactly do you "run WikiBlame from *cz* history page"?

**Comment by zemiak1** [comment]
go to CS.wikipedia article eg C++
  https://cs.wikipedia.org/wiki/C%2B%2B
view history (Zobrazit historii)
  https://en.wikipedia.org/w/index.php?title=C%2B%2B&action=history
click "Revision history search" ( Prohledávání starších verzí)
  http://wikipedia.ramselehof.de/wikiblame.php?article=C%2B%2B
there
  Language: sk _(incorrect)_         Display Language: sk _(ok)_

If I try it on EN.wikipedia it works correct.
  http://wikipedia.ramselehof.de/wikiblame.php?lang=en&article=C%2B%2B
So may be it is wrong of czech wiki page.

**Comment by FlominatorTM** [comment]
Please make an administrator add "&lang=cs" to the url at https://cs.wikipedia.org/wiki/MediaWiki:Histlegend

**Comment by zemiak1** [comment]
Request added to cs. 'histlegend' discusion.

**Comment by zemiak1** [comment]
OK, they changed it, now it works correct. Thank you for advice.
